server:
  port: 8001


#mybatis配置
mybatis:
  type-aliases-package: com.strive.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml


#Spring配置
spring:
  application:
    name: springcloud-provider-dept #3个服务名称一致
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://152.136.142.49:3306/db_01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

#eureka配置 配置服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: springcloud-provider-dept-8001  #实例名
    prefer-ip-address: true  #为true 可以展示id

info:
  company.name: strive-springcloud-provider