server:
  port: 7001

spring:
  application:
    name: springcloud-eureka-dept-7001

#eureka 配置
eureka:
  instance:
    hostname: localhost #eureka服务端的实例名称
  client:
    register-with-eureka: true #表示是否向eureka注册中心注册自己
    fetch-registry: false #fetch-registry为false表示自己是注册中心
    service-url: #监控页面
      #单机：http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群：关联 每台地址 用 , 分割
      defaultZone: http://localhost:7001/eureka/
