server:
  port: 80

spring:
  application:
    name: springcloud-consumer-dept

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
    register-with-eureka: false #不向注册中心注册自己

feign:
  hystrix:
    enabled: true #开启服务降级